# POST http://localhost:8000/register/
# Content-Type: application/json

# {
#     "email":"jc10@email.com",
#     "first_name":"Jules",
#     "last_name":"C",
#     "gender":"M",
#     "birthdate":"2004-09-09",
#     "password":"mot_de_passe",
#     "password_confirm":"mot_de_passe"

# }

# POST http://localhost:8000/login/
# Content-Type: application/json

# {
#     "email":"jc10@email.com",
#     "username":"jc10@email.com",
#     "password":"mot_de_passe"
# }

# POST http://localhost:8001/logout/ 
# Content-Type: application/json" 
# Authorization: Bearer "put_the_user_token_here" 
